### PR TITLE
Localization English/Ukrainian

### PR DESCRIPTION
**Pull request by yuchdev**
#### EDIT

As requested, I split the last PR into two, and this request is dedicated completely to localization.

As of now, the application supports 2 languages: English and Ukrainian. 
The default language set by the command line is Ukrainian, but it is likely to be changed as soon as we expand our community to other countries.

This opens for us the whole international audience and opensource community, so I would've advertised this change to the international IT army groups.

Also, `README.md` is completely translated into English (see `README-EN.md`).

### Ways of configuration

There are two ways to change the interface language:

#### 1. Using command line
    python3 runner.py --lang EN https://ria.ru
    python3 runner.py --lang UA https://ria.ru

Most likely, this is the way most Python users prefer to change it. 

#### 2. Using environment variable
    export MHDDOS_LANG=EN
    python3 runner.py https://ria.ru

An environment variable is easy to pass into the Docker container with the `-e` option

    docker run -e MHDDOS_LANG=UA -it --rm --log-driver none --name multidd --pull always karboduck/multidd

### Implementation considerations

As I mentioned in the issue thread, English localization serves as a key to all others, so it can't be "lost", and we fall back into English in case of any problems with translation. 

New languages should be added in the `translations` directory of the project root, and have an `ua.json` naming convention. After adding a new translation file, its ISO two-symbol code should be added in the `--lang` command-line option.

The translation file itself is extremely straightforward, with the plain key-value format:
```
{
  "Downloading a proxy...": "Завантажуємо проксі...",
  "No working proxies found - stop the attack": "Не знайдено робочих проксі - зупиняємо атаку",
  "Selected": "Обрано",
  "targets to attack": "цілей для атаки",
  "Attacking the target:": "Атакуємо ціль:",
  ...
}
```

In the application itself translation also looks very straightforward. The call

`TR('Launching the attack ...')`
would start lookup into the active dictionary, and will probably find the value
```
{
...
  "Launching the attack ...": "Запускаємо атаку..."
...
}
```
If for some reason we don't find the value, an English translation would be displayed.

## Note 1

I did not add a link to `README-EN.md` into the `README.md`, because I'm not sure about a better layout.

### Entire README in English by default

And links to all other supported languages in the `Documentation` section

Entire README in English by default

### README is just for choosing the supported language

In this case, the README has just a list of supported languages

README is just for choosing the supported language

## Note 2

We should understand the scale of such improvement, and probably need to introduce it gradually.
I left `--lang UA` option by default, so that users were not shocked by sudden changes, but after some beta-testing, we can switch to EN by default.

I accept any inquiries regarding the pull request, and am open to meaningful discussion.

### CODE REVIEW

**Comment by porthole-ascend-cinnamon** [comment]
I would greatly prefer to separate PRs for i18n and for stored config. i18n can be done with the cli switch with default UA and does not require to store config file.

**Comment by yuchdev** [comment]
Agreed, I'll try to find time tomorrow. 
I suggest considering localization PR first, and then PR for config file (so that it already included `lang` option). Honestly, config is just quite handy to me, so I reasoned that someone else may like it too.

**Comment by porthole-ascend-cinnamon** [comment]
You are the best! We'll need some time to review and make some adjustments, it you don't mind, but great work overall.

**Comment by yuchdev** [comment]
@porthole-ascend-cinnamon 
Take a look please, these are final fixes.

**Comment by porthole-ascend-cinnamon** [comment]
I made "some" changes (quite a lot, I know). I hope you won't be offended by the amount of rewrite - your contribution is still highly appreciated and valuable. Among the most serious changes - I've decided to combine all translations into one file, so it's easier to modify in one place. I also get rid of the env variable - I don't really see a real use case for it, since you can pass arguments to docker as well, and I was able to get rid of some code (less code = less maintainance). 
Please review my changes if you have time.

**Comment by yuchdev** [comment]
No problem at all, you're the maintainer of the application, so you have an ultimate right to decide which code you'd be able to maintain. 

I was glad to help in any way, and hope to keep doing it in future . 
You can merge the PR.

**Comment by yuchdev** [comment]
@porthole-ascend-cinnamon 
Just to clarify - will you merge the PR, or you expect me to merge? Different projects have different processes

**Comment by porthole-ascend-cinnamon** [comment]
Just needed some more testing/polishing, sorry for the confusion @yuchdev

**Pull request merged**
