### PR TITLE
Add code improvements

### PR DESCRIPTION
**Pull request by parfeniukink**

### CODE REVIEW

**Comment by parfeniukink** [comment]
1. Some code quality issues were resolved
2. Created a sample of the divisional project layout

**Comment by porthole-ascend-cinnamon** [comment]
Hi, thanks for the PR, but I won't merge it, sorry. That's not the kind of help I seek at the moment.

**Comment by parfeniukink** [comment]
@porthole-ascend-cinnamon Please write if I can help with something.
P.S. I have some exp in Python / CyberSec

**Comment by porthole-ascend-cinnamon** [comment]
@parfeniukink You can probably help by reviewing the existing attack methods or suggesting new methods. Most asked for is DDoS-Guard bypass, but it feels like almost impossible to implemented.

**Pull request closed without merging**
